// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.27.2
// source: node/v1/node.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NodeChannelClient is the client API for NodeChannel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeChannelClient interface {
	// Connect 在单一连接纪元内交换注册、心跳、任务租约和结果消息。
	Connect(ctx context.Context, opts ...grpc.CallOption) (NodeChannel_ConnectClient, error)
}

type nodeChannelClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeChannelClient(cc grpc.ClientConnInterface) NodeChannelClient {
	return &nodeChannelClient{cc}
}

func (c *nodeChannelClient) Connect(ctx context.Context, opts ...grpc.CallOption) (NodeChannel_ConnectClient, error) {
	stream, err := c.cc.NewStream(ctx, &NodeChannel_ServiceDesc.Streams[0], "/novagrid.node.v1.NodeChannel/Connect", opts...)
	if err != nil {
		return nil, err
	}
	x := &nodeChannelConnectClient{stream}
	return x, nil
}

type NodeChannel_ConnectClient interface {
	Send(*AgentMessage) error
	Recv() (*ControlMessage, error)
	grpc.ClientStream
}

type nodeChannelConnectClient struct {
	grpc.ClientStream
}

func (x *nodeChannelConnectClient) Send(m *AgentMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *nodeChannelConnectClient) Recv() (*ControlMessage, error) {
	m := new(ControlMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NodeChannelServer is the server API for NodeChannel service.
// All implementations must embed UnimplementedNodeChannelServer
// for forward compatibility
type NodeChannelServer interface {
	// Connect 在单一连接纪元内交换注册、心跳、任务租约和结果消息。
	Connect(NodeChannel_ConnectServer) error
	mustEmbedUnimplementedNodeChannelServer()
}

// UnimplementedNodeChannelServer must be embedded to have forward compatible implementations.
type UnimplementedNodeChannelServer struct {
}

func (UnimplementedNodeChannelServer) Connect(NodeChannel_ConnectServer) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedNodeChannelServer) mustEmbedUnimplementedNodeChannelServer() {}

// UnsafeNodeChannelServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeChannelServer will
// result in compilation errors.
type UnsafeNodeChannelServer interface {
	mustEmbedUnimplementedNodeChannelServer()
}

func RegisterNodeChannelServer(s grpc.ServiceRegistrar, srv NodeChannelServer) {
	s.RegisterService(&NodeChannel_ServiceDesc, srv)
}

func _NodeChannel_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NodeChannelServer).Connect(&nodeChannelConnectServer{stream})
}

type NodeChannel_ConnectServer interface {
	Send(*ControlMessage) error
	Recv() (*AgentMessage, error)
	grpc.ServerStream
}

type nodeChannelConnectServer struct {
	grpc.ServerStream
}

func (x *nodeChannelConnectServer) Send(m *ControlMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *nodeChannelConnectServer) Recv() (*AgentMessage, error) {
	m := new(AgentMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NodeChannel_ServiceDesc is the grpc.ServiceDesc for NodeChannel service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeChannel_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "novagrid.node.v1.NodeChannel",
	HandlerType: (*NodeChannelServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _NodeChannel_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "node/v1/node.proto",
}
